// packages/core/src/index.ts
export * from "./domain/ast";
export * from "./domain/branchMetrics";
export * from "./domain/analysisScope";
export * from "./domain/metricCatalog";
export * from "./domain/testGovernance";
export * from "./domain/testFacts";
export * from "./domain/testAssociations";
export * from "./domain/testGovernanceCoverage";
export * from "./domain/testProviderCoverage";
export * from "./domain/validationEvidence";
export * from "./domain/governance";
export * from "./domain/persistenceBoundary";
export * from "./domain/calibration";
export * from "./domain/structuralPolicy";
export * from "./domain/symbolCalibration";
export * from "./domain/symbolScopeMetric";
export * from "./domain/symbolScopeShadowEvidence";
export * from "./domain/graph";
export * from "./domain/reach";
export * from "./domain/confidence";
export * from "./domain/alpha";
export * from "./domain/weights";
export * from "./domain/mrDiagnosis";
export * from "./languageSupport";
export * from "./projectFiles";
export { GOVERNANCE_POPULATIONS, effectiveFileKind, participatesInPopulation } from "./domain/fileParticipation";
export type { GovernancePopulation } from "./domain/fileParticipation";
export * from "./runtimeAssets";
export * from "./domain/i-push";
export { computeCohesion, computeConnectedness } from "./domain/cohesion";
export { p95 } from "./domain/p95";
export { computeCRLState, computeCRLStateBreakdown, DEFAULT_CRL_STATE_WEIGHTS } from "./domain/crlState";
export type { P95Values, CRLStateWeights, CRLStateInput, CRLStateComponents, CRLStateBreakdown } from "./domain/crlState";
export * from "./domain/crl";
export * from "./domain/historyRetention";
export * from "./errors/errors";
export * from "./port/ParserService";
export * from "./port/SemanticToolchainDiscovery";
export * from "./port/SemanticRelationService";
export * from "./port/StorageService";
export * from "./port/SymbolCalibrationStore";
export * from "./port/ScanProgressService";
export { RuleService, RuleCompileError } from "./port/RuleService";
export * from "./port/LockService";
export * from "./application/scan";
export { writeInitConfig } from "./application/initConfig";
export { readCoordinationConfig } from "./application/coordinationConfig";
export type { CoordinationConfigReadResult } from "./application/coordinationConfig";
export * from "./coordination/CoordinationClient";
export * from "./coordination/ScopeTemplates";
export { readHistoryRetentionPolicy, DEFAULT_HISTORY_RETENTION } from "./application/governancePersistence";
export { installDefaultScripts } from "./application/defaultScripts";
export { initApp } from "./application/initApp";
export { AGENT_SKILL_TARGETS, installAgentSkill } from "./application/agentSkill";
export type { AgentSkillTarget, AgentSkillLocale, AgentSkillInstallInput, AgentSkillInstallResult } from "./application/agentSkill";
export { gateApp } from "./application/governance/gateApp";
export type { GateAppOutput, GateDiagnostic, GateUnavailableReason } from "./application/governance/gateApp";
export { sealPendingEvidence } from "./application/governance/sealPendingEvidence";
export type { SealPendingEvidenceOptions, SealPendingEvidenceResult } from "./application/governance/sealPendingEvidence";
export type { GateFileMetric, GateRenderResult, GateReportFacts } from "./application/governance/gateReport";
export { testGovernance } from "./application/testGovernance";
export type { TestGovernanceReport } from "./application/testGovernance";
export { testGovernanceProviderList } from "./test-governance/catalog";
export * from "./application/diff";
export { rebuildGraph } from "./application/diffGraph";
export type { RebuiltGraph } from "./application/diffGraph";
export { computeFileImpact } from "./application/diffImpact";
export type { ImpactInput, ImpactOutput } from "./application/diffImpact";
export * from "./application/governance/gate";
export { loadGateConfig } from "./application/governance/gateConfig";
export * from "./application/governance/review";
export * from "./application/record";
export * from "./application/status";
export * from "./application/governanceReadiness";
export * from "./application/governance/governanceDiagnostics";
export * from "./application/governance/evaluateGovernance";
export * from "./application/governance/governanceFactProjection";
export * from "./application/governance/testGovernanceProjection";
export * from "./application/governance/calibrationSignals";
export * from "./application/governance/calibrationGate";
export * from "./hook/HookLauncher";
export * from "./document-store/DocumentStore";
export * from "./document-store/DocumentSimilarity";
export * from "./application/configAudit";
export { associateFromUrl, associateFromLocal, unlinkDocsRepo, statusDocsRepo, checkSyncStatus } from "./docs-repo/DocsRepoManager";
export type { DocsRepoConfig, SyncStatus, StatusResult } from "./docs-repo/DocsRepoManager";
// path_class 工具（parsePathClasses + layerWeightOf，gateApp + diff 共用）
export { parsePathClasses, layerWeightOf, classifyPath } from "./application/pathClass";
export type { PathClass } from "./application/pathClass";
// adapter exports (cli needs these to assemble LiveLayer)
export * from "./adapter/parser/ParserFactory";
export * from "./adapter/storage/JsonFileStorage";
export * from "./adapter/storage/ScanProgressFile";
export { inspectBaselineGenerations } from "./adapter/storage/BaselineGenerationDiagnostics";
export type { BaselineGenerationArtifact, BaselineGenerationDiagnostics } from "./adapter/storage/BaselineGenerationDiagnostics";
export * from "./adapter/rule/CelAdapter";
export * from "./adapter/lock/AdvisoryLock";
// infra path helpers (CLI uses these to avoid hardcoded ".openarch/" strings)
export { openarchBase, baselineDir, baselineIndex, configPath, historyDir, docsRepoDir, implicitDepsPath, implicitDepsRulesDir, testGovernanceRulesDir, projectRoot, toRelative, toAbsolute } from "./infra/paths";
export { globSync } from "./infra/glob";
// 隐式依赖发现引擎
export { discover } from "./application/discover";
export type { DiscoverInput, DiscoverReport } from "./application/discover";
export { executeRule } from "./implicit-deps/engine";
export { readImplicitDepsYml, mergeBySource, writeImplicitDepsYml } from "./implicit-deps/merge";
export type { DiscoveredEdge, StoredEdge, ImplicitDependencyRule } from "./implicit-deps/types";
export { executeTestFindingScript } from "./test-governance/engine";
export type { TestFindingScript, TestScriptResult } from "./test-governance/engine";
export type { ProjectTestExecution, TestExecutionRunner } from "./test-governance/runner";
export { runProjectProcess, DEFAULT_PROJECT_PROCESS_TIMEOUT_MS, DEFAULT_PROJECT_PROCESS_OUTPUT_LIMIT } from "./test-governance/runners/projectProcess";
export type { ProjectProcessOptions } from "./test-governance/runners/projectProcess";
export type { TestFrameworkProvider, TestProviderResult } from "./test-governance/provider";
export { antiPatterns } from "./application/antiPatterns";
export type { AntiPatternReport } from "./application/antiPatterns";
export { loadScriptFacts } from "./application/scriptFacts";
export type { ScriptFactBaseline, ScriptFactsOptions } from "./application/scriptFacts";
export { executeStagedScript } from "./staged-analysis/engine";
export { SCRIPT_AST_FACTS } from "./staged-analysis/types";
export { createProjectFacts, emptyProjectFacts, unavailableRequiredFact, isScriptFactRequirements, scriptFactRequirementsError, PROJECT_FACTS_VERSION, SCRIPT_FACT_CAPABILITIES } from "./script-runtime/projectFacts";
export type { ProjectFacts, ProjectFactsInput, ScriptFactCapability, FactAvailability, FactResult, ScriptFileFact, StructureMetricFact, SemanticRelationsFact, ScriptAuthorityContract, ScriptAuthorityDeclaration, ChangeSurfaceFact, ChangeSurfaceSymbolFact } from "./script-runtime/projectFacts";
export type { ScriptFactCapabilityDescription } from "./script-runtime/projectFacts";
export type { InvocationBindingFact } from "./domain/invocationBindings";
export { SCRIPT_STARTERS, scriptStarter } from "./script-runtime/scriptStarters";
export type { ScriptStarter, ScriptStarterId } from "./script-runtime/scriptStarters";
export { defaultScriptAssets, recommendedAntiPatternAssets } from "./script-runtime/defaultScriptAssets";
export type { DefaultScriptAsset, DefaultScriptAssetKind } from "./script-runtime/defaultScriptAssets";
export { evolutionReview } from "./application/evolutionReview";
export type { EvolutionReviewReport } from "./application/evolutionReview";
export type { EvolutionSignalReport, CochangeSetAnalysis, CochangeSetCandidate, ExtensionSurfaceAnalysis, ExtensionSurfaceCandidate } from "./domain/evolutionSignals";
export { collectGitCommitHistory } from "./application/changeSet";
export { collectGitChangeSet, collectGitRevisionChangeSet, type ChangeSetOptions, type ChangeSetPopulation } from "./application/changeSet";
export { analyzeChangeSetSemantics, type SemanticDiffReport, type SemanticBeforeState, type SemanticFileProfile } from "./application/semanticDiff";
export { analyzeSemanticChanges, type SemanticChange } from "./domain/semanticChanges";
export { buildImpactPlan, symbolUseDemandForProfiles, type ImpactPlanItem, type ImpactPlanAction, type SymbolConsumerEvidence } from "./application/impactPlan";
export { computeChangeSurfaceForProfiles, type FileChangeSurface, type ChangeSurfaceForProfilesInput } from "./application/changeSurface";
export type { ChangeSurfaceResult, ChangeSurfaceContribution, ChangeSurfaceProvenance, ChangeSurfaceInput } from "./domain/changeSurfaceImpact";
export { reconcileBaseline, orphanedBaselinePaths } from "./application/baselineReconciliation";
export { checkExtensionContracts } from "./application/extensions";
export { evaluateAuthorityHygieneQuality, loadAuthorityHygieneConfig, parseAuthorityHygieneConfig } from "./application/authorityHygiene";
export type { AuthorityHygieneConfig, AuthorityHygieneQualityAction, AuthorityHygieneQualityResult } from "./application/authorityHygiene";
export { collectSymbolUseReports } from "./application/symbolHygiene";
export { prefilterStaticBoundEmpty, staticConsumerFilesFor } from "./application/symbolHygiene";
export { collectSymbolRevisionSnapshot, collectSymbolVersionPair, collectLspSymbolVersionPair, collectTypeScriptSymbolVersionPair } from "./application/symbolVersionPair";
export { assessSymbolScopeAdmissions } from "./application/symbolScopeAdmission";
export { recordSymbolCalibrationProfile, loadSymbolCalibrationProfiles } from "./application/symbolCalibration";
export type { SymbolCalibrationObservationInput } from "./application/symbolCalibration";
export { evaluatePersistedSymbolScopeShadowEvidence } from "./application/symbolScopeShadowEvidence";
export type { SymbolUseDemand } from "./port/SymbolUseService";
export type { AntiPatternCategory, AntiPatternHit, AntiPatternHitInput, AntiPatternRule, AntiPatternSeverity } from "./anti-patterns/engine";
export { SymbolUseServiceLive, PROVIDERS as SYMBOL_USE_PROVIDERS } from "./adapter/symbol-use/SymbolUseServiceLive";
export { nonLspProviderLanguages, symbolUseRequestPolicy } from "./adapter/symbol-use/requestPolicy";
export { jdtlsDaemonPort, startJdtlsDaemon, stopJdtlsDaemon, jdtlsDaemonStatus, jdtlsDaemonStateFile, runJdtlsDaemonProcess, jdtlsDaemonStateFile as jdtlsDaemonStateFileOf } from "./adapter/symbol-use/jdtlsDaemon";
export { nodeToolchainRuntime } from "./adapter/toolchain/NodeToolchainRuntime";
export { jdtlsDataDir } from "./adapter/symbol-use/JavaSymbolUseProvider";
export { symbolUseDeclarationFamily, symbolUseFamiliesFor, symbolUseScopeFor } from "./symbol-use/types";
export type { SymbolUseReport, SymbolUseFact, SymbolReference, SymbolUseAvailability, SymbolUseCoverage, SymbolUseEvidenceSource, SymbolUseScope, SymbolUseDeclarationFamily } from "./symbol-use/types";
export { assessSymbolScopeImpactAdmission } from "./domain/symbolScopeAdmission";
export type { SymbolScopeImpactAdmission, SymbolScopeAdmissionRequirement, SymbolScopeAdmissionRequirementId } from "./domain/symbolScopeAdmission";
export type { SymbolRevisionAvailability, SymbolRevisionSnapshot, SymbolVersionedPopulation, SymbolDeclarationPair, SymbolDeclarationPairStatus, SymbolVersionPairReport } from "./domain/symbolVersionPair";
export { symbolVersionDeclarationIdentity, pairVersionedSymbolDeclarations, commonSymbolVersionedPopulation } from "./domain/symbolVersionPair";
export { SemanticRelationServiceLive } from "./adapter/semantic-relations/SemanticRelationServiceLive";
export { collectTypeScriptSemanticRelations } from "./semantic-relations/typescript";
export type { SemanticRelationFact, SemanticRelationKind, SemanticRelationReport, SemanticRelationSymbol } from "./semantic-relations/types";
export { SemanticToolchainDiscoveryLive } from "./adapter/toolchain/SemanticToolchainDiscoveryLive";
export { discoverSemanticToolchains } from "./toolchain/discovery";
export { initializeToolchainConfig } from "./application/toolchainConfigSetup";
export { checkForUpdates, compareVersions, fetchLatestVersion, REMOTE_TAGS_URL } from "./application/updateCheck";
export type { UpdateCheckResult } from "./application/updateCheck";
export { projectToolchainConfigPath, readToolchainConfiguration, toolchainConfigPaths, userToolchainConfigPath } from "./toolchain/config";
export type { ToolchainConfigScope, ToolchainConfiguration, ToolchainConfigPaths, ToolchainExecutableOverride } from "./toolchain/config";
export type { SemanticToolchainAvailability, SemanticToolchainDiscoveryRequest, SemanticToolchainFact, SemanticToolchainKind, SemanticToolchainLocation, SemanticToolchainReport, ToolchainCommandResult, ToolchainRuntime } from "./toolchain/types";
export { decodeJsonRpc, encodeJsonRpc } from "./lsp/jsonRpc";
export type { JsonRpcMessage } from "./lsp/jsonRpc";
export { startNodeLspSession } from "./adapter/lsp/NodeLspSession";
export type { LspSession } from "./adapter/lsp/NodeLspSession";
