// Generate GitHub Release notes from CHANGELOG.md plus an explicit download
// section. Source archives are auto-generated by GitHub; this script makes the
// paths visible in the release body instead of hiding them under Assets.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const changelogPath = join(root, "CHANGELOG.md");
const versionArg = process.argv[2];
const outputPath = process.argv[3] ?? join(root, ".release-notes.md");

if (!versionArg) {
  console.error("用法: node scripts/release-notes.mjs <version> [output.md]");
  process.exit(2);
}

const version = versionArg.replace(/^v/, "");
const tag = `v${version}`;
const changelog = readFileSync(changelogPath, "utf8");

const lines = changelog.split(/\r?\n/);
const headerIndex = lines.findIndex((line) => /^##\s+\[?v?/.test(line) && line.includes(`[${version}]`));
if (headerIndex < 0) {
  console.error(`CHANGELOG.md 中未找到版本段落: [${version}]`);
  process.exit(1);
}
const nextHeader = lines.slice(headerIndex + 1).findIndex((line) => /^##\s/.test(line));
const sectionLines = nextHeader >= 0
  ? lines.slice(headerIndex, headerIndex + 1 + nextHeader)
  : lines.slice(headerIndex);
const changelogSection = sectionLines.join("\n").trim();

const notes = `${changelogSection}

## 下载

### 源码（GitHub 自动生成）

- [Source code (tar.gz)](https://github.com/VilTea/openarch/archive/refs/tags/${tag}.tar.gz)
- [Source code (zip)](https://github.com/VilTea/openarch/archive/refs/tags/${tag}.zip)

### 可安装产物

- npm tarballs: 见下方 Assets（@openarch/core / @openarch/cli / @openarch/plugin）
- 原生二进制: 见下方 Assets（Linux / Windows / macOS zip）
- 安装方式示例:

\`\`\`bash
# npm tarball 安装（跨平台）
npm install -g @openarch/cli-${version}.tgz

# 或解压对应平台二进制 zip，把 openarch 加入 PATH
\`\`\`
`;

writeFileSync(outputPath, `${notes}\n`, "utf8");
console.log(`已生成 Release notes: ${outputPath}`);
