import { readFileSync } from "node:fs";
import { atomicWriteTextSync } from "../adapter/storage/AtomicWriter";
import type { DocumentStore } from "./DocumentStore";
import { documentRelationsPath } from "./DocumentStore";
import { readDocumentIndex } from "./DocumentIndex";
import { findDocumentSimilarityCandidates, type DocumentSimilarityCandidate } from "./DocumentSimilarityCandidates";

export type DocumentDispositionDecision = "merged" | "related" | "kept-separate";

export interface DocumentDisposition {
  readonly left: string;
  readonly right: string;
  readonly decision: DocumentDispositionDecision;
  readonly note?: string;
  readonly at: string;
}

interface DocumentRelationsFile {
  readonly version: "1";
  readonly relations: readonly unknown[];
  readonly dispositions?: readonly DocumentDisposition[];
}

const DECISIONS: ReadonlySet<string> = new Set(["merged", "related", "kept-separate"]);

const validPath = (path: string): boolean => path.length > 0 && !path.startsWith("../") && path !== "..";

const validDisposition = (value: unknown): value is DocumentDisposition => {
  if (!value || typeof value !== "object") return false;
  const record = value as Record<string, unknown>;
  return typeof record.left === "string" && validPath(record.left)
    && typeof record.right === "string" && validPath(record.right)
    && typeof record.decision === "string" && DECISIONS.has(record.decision)
    && typeof record.at === "string"
    && (record.note === undefined || typeof record.note === "string");
};

const rawRelations = (store: DocumentStore): { readonly version: "1"; readonly relations: readonly unknown[] } => {
  try {
    const value = JSON.parse(readFileSync(documentRelationsPath(store), "utf8")) as DocumentRelationsFile;
    if (value.version === "1" && Array.isArray(value.relations)) return { version: "1", relations: value.relations };
  } catch { /* regenerated by initializeProjectDocumentStore */ }
  return { version: "1", relations: [] };
};

export const readDocumentDispositions = (store: DocumentStore): readonly DocumentDisposition[] => {
  try {
    const value = JSON.parse(readFileSync(documentRelationsPath(store), "utf8")) as DocumentRelationsFile;
    if (value.version !== "1" || !Array.isArray(value.relations)) return [];
    return Array.isArray(value.dispositions) && value.dispositions.every(validDisposition) ? value.dispositions : [];
  } catch {
    return [];
  }
};

const dispositionPair = (left: string, right: string): string => [left, right].sort().join("\u0000");

export const recordDocumentDisposition = (
  store: DocumentStore,
  input: { readonly left: string; readonly right: string; readonly decision: DocumentDispositionDecision; readonly note?: string; readonly at?: string },
): { readonly error: string } | { readonly path: string; readonly replaced: boolean } => {
  const left = input.left.trim();
  const right = input.right.trim();
  if (!validPath(left) || !validPath(right) || left === right) {
    return { error: "处置两端必须是文档库 scope 内两条不同的相对路径" };
  }
  if (!DECISIONS.has(input.decision)) return { error: "decision 必须是 merged、related 或 kept-separate" };
  const path = documentRelationsPath(store);
  const existing = readDocumentDispositions(store);
  const pair = dispositionPair(left, right);
  const replaced = existing.some((entry) => dispositionPair(entry.left, entry.right) === pair);
  const disposition: DocumentDisposition = {
    left, right, decision: input.decision,
    ...(input.note?.trim() ? { note: input.note.trim() } : {}),
    at: input.at ?? new Date().toISOString(),
  };
  const next = existing.filter((entry) => dispositionPair(entry.left, entry.right) !== pair);
  next.push(disposition);
  const preserved = rawRelations(store);
  atomicWriteTextSync(path, `${JSON.stringify({ version: "1", relations: preserved.relations, dispositions: next }, null, 2)}\n`);
  return { path, replaced };
};

const hasDisposition = (candidate: DocumentSimilarityCandidate, dispositions: readonly DocumentDisposition[]): boolean =>
  dispositions.some((entry) => dispositionPair(entry.left, entry.right) === dispositionPair(candidate.left, candidate.right));

/** Similarity candidates in the current index that no disposition has resolved yet. */
export const unresolvedSimilarityCandidates = (store: DocumentStore): readonly DocumentSimilarityCandidate[] => {
  const index = readDocumentIndex(store);
  const entries = new Map(Object.entries(index.entries));
  if (entries.size === 0) return [];
  const dispositions = readDocumentDispositions(store);
  const all = [...entries.keys()];
  return findDocumentSimilarityCandidates(entries, new Set(all), store.scopeId)
    .filter((candidate) => !hasDisposition(candidate, dispositions));
};
